repos:
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
    - id: mdformat
      additional_dependencies:
        - mdformat-gfm
        - mdformat-frontmatter
        - mdformat-footnote
        - mdformat-gfm-alerts
