[package]
name = "reading-group-theme"
version = "0.1.3"
entrypoint = "src/lib.typ"
authors = ["Dimitri Kokkonis (kokkonisd@gmail.com)"]
license = "CC-BY-NC-SA-4.0"
description = "A Touying-based theme for presentations."
